### ISSUE TITLE
crowi.min.jsが正しく生成されていない

### ISSUE THREAD

**Issue by EmEpsilon** [crowi/docker-crowi#3]
docker imageで生成されているpublic/js/crowi.min.jsが正しく生成されておらず、
ログイン画面の新規登録画面やCreate Portalボタンが正しく動作しません。

バージョンはv1.5.0です。

**Comment by Bakudankun** [comment]
報告ありがとうございます！！

確かに、11/1あたりのビルドから正しく動作しなくなっているようです。
どうやら一部のプラグイン（たぶんwebpackあたり）がアップデートされたことが関係していそうです。

すぐに対応することは難しそうなので、もし急を要するのであれば、ひとまず`bakudankun/crowi:latest`の代わりに10/25のビルド

```
bakudankun/crowi@sha256:d05a51a5b6327b10dbc469a9eab8ef61b984760b8754cbfc4c2f8bd00c48e8fa
```

を利用してください。

**Comment by EmEpsilon** [comment]
対応ありがとうございます。

取り敢えずは、10/25のビルドで対応しようと思います。

**Comment by Bakudankun** [comment]
[Crowiのv1.5.1](https://github.com/crowi/crowi/releases/tag/v1.5.1)にて修正されたのでアップデートしておきました。

あと、ついでにelasticsearchを用意する推奨の方法も変えたので、READMEの`docker-compose.yml`の例をご確認ください。
